# Etapa 1: Construcción con Vite
FROM node:18 AS builder

WORKDIR /app
COPY package*.json ./
COPY tsconfig.* ./
COPY vite.config.* ./
RUN npm install

COPY . .
RUN npm run build

# Etapa 2: Servir con Nginx
FROM nginx:alpine

# Copiamos el build de Vite
COPY --from=builder /app/dist /usr/share/nginx/html

# Opcional: configura Nginx para rutas SPA (react-router-dom)
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
